# Generated by Django 4.0 on 2021-12-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('date_of_death', models.DateField(null=True)),
                ('country', models.CharField(max_length=100)),
                ('portrait', models.ImageField(upload_to='portraits/')),
                ('bio', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('short_description', models.CharField(default='', max_length=500)),
                ('page_count', models.PositiveIntegerField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('de', 'German'), ('fr', 'French')], max_length=3)),
                ('publishing_year', models.SmallIntegerField()),
                ('cover_type', models.CharField(choices=[('soft', 'Soft'), ('hard', 'Hard')], max_length=10)),
                ('cost', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to='book_pictures/')),
                ('authors', models.ManyToManyField(related_name='books', to='bookshop.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookshop.publisher')),
            ],
        ),
    ]
