# Generated by Django 4.0 on 2021-12-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='portraits/'),
        ),
    ]
