# Generated by Django 4.0 on 2021-12-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_alter_author_date_of_death_alter_author_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
