# Generated by Django 4.0 on 2022-03-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_alter_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
